### PR TITLE
Add initial server tests.

### PR DESCRIPTION
**Pull request by sgomes**
Please take a look and let me know what you think. Does this structure make sense? Also, I've moved all the server-side code to ES Modules, for consistency with our eventual client-side code; we probably don't want to have our codebase split between ESM and CJS.

Changes:
- Adds server tests.
- Changes all server and shared code to ES modules. Uses Babel to transpile server code.
- Moves pie model to shared code.
- Adds client test directory for future client tests to go.

### CODE REVIEW

**Comment by sgomes** [comment]
Implements part of #2.

**Comment by sgomes** [comment]
Pinging reviewers :)

**Comment by samdutton** [comment]
LGTM.

**Comment by devnook** [comment]
LGTM too

**Pull request merged**
